services:

  hedge-fund:
    build: .
    image: ai-hedge-fund
    volumes:
      - ./.env:/app/.env
    command: python src/main.py --ticker AAPL,MSFT,NVDA
    environment:
      - PYTHONUNBUFFERED=1
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - OLLAMA_HOST=host.docker.internal
    tty: true
    stdin_open: true
    network_mode: "host"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  hedge-fund-reasoning:
    build: .
    image: ai-hedge-fund
    volumes:
      - ./.env:/app/.env
    command: python src/main.py --ticker AAPL,MSFT,NVDA --show-reasoning
    environment:
      - PYTHONUNBUFFERED=1
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - OLLAMA_HOST=host.docker.internal
    tty: true
    stdin_open: true
    network_mode: "host"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  hedge-fund-ollama:
    build: .
    image: ai-hedge-fund
    volumes:
      - ./.env:/app/.env
    command: python src/main.py --ticker AAPL,MSFT,NVDA --ollama
    environment:
      - PYTHONUNBUFFERED=1
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - OLLAMA_HOST=host.docker.internal
    tty: true
    stdin_open: true
    network_mode: "host"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  backtester:
    build: .
    image: ai-hedge-fund
    volumes:
      - ./.env:/app/.env
    command: python src/backtester.py --ticker AAPL,MSFT,NVDA
    environment:
      - PYTHONUNBUFFERED=1
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - OLLAMA_HOST=host.docker.internal
    tty: true
    stdin_open: true
    network_mode: "host"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  backtester-ollama:
    build: .
    image: ai-hedge-fund
    volumes:
      - ./.env:/app/.env
    command: python src/backtester.py --ticker AAPL,MSFT,NVDA --ollama
    environment:
      - PYTHONUNBUFFERED=1
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - OLLAMA_HOST=host.docker.internal
    tty: true
    stdin_open: true
    network_mode: "host"
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  ollama_data: 